TOP                     ::= ../..
BOARD                   ::= esp32c3_devkitm

ESP32_CHIP              ::= esp32c3
ESP32_TRIPLE            ::= riscv64-zephyr-elf
ESP32_APPIMAGE_OFFSET   ::= 0x42000000
ESP32_FLASH_START       ::= 0x00000000
ESP32_FLASH_END         ::= 0x00400000
ESP32_SRAM_START        ::= 0x3fc80000
ESP32_SRAM_END          ::= 0x3fce0000

include $(TOP)/mk/esp32.mk
