TOP                     ::= ../..
BOARD                   ::= esp32c6_devkitc

ESP32_CHIP              ::= esp32c6
ESP32_TRIPLE            ::= riscv64-zephyr-elf
ESP32_APPIMAGE_OFFSET   ::= 0x42000000
ESP32_FLASH_START       ::= 0x00000000
ESP32_FLASH_END         ::= 0x00800000
ESP32_SRAM_START        ::= 0x40800000
ESP32_SRAM_END          ::= 0x40850000

include $(TOP)/mk/esp32.mk
